//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_end_of_day_transactions
    {
        public int autonum { get; set; }
        public Nullable<System.DateTime> date_trans { get; set; }
        public Nullable<decimal> cash_begin { get; set; }
        public Nullable<decimal> cash_release { get; set; }
        public Nullable<decimal> cash_collected { get; set; }
        public Nullable<decimal> cash_pulled_out { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<decimal> cash_end { get; set; }
    }
}
