//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment
    {
        public int autonum { get; set; }
        public string reference_no { get; set; }
        public Nullable<System.DateTime> date_trans { get; set; }
        public Nullable<int> payor_id { get; set; }
        public string payor_name { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    }
}
