//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_payment_details
    {
        public int autonum { get; set; }
        public string reference_no { get; set; }
        public string payment_type { get; set; }
        public string loan_no { get; set; }
        public string loan_name { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public string created_by { get; set; }
    }
}
