//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loan_processing_amortization_schedule
    {
        public int autonum { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<decimal> principal { get; set; }
        public Nullable<decimal> interest { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string createdby { get; set; }
        public string loan_no { get; set; }
    }
}
