//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_customer
    {
        public int autonum { get; set; }
        public string customer_no { get; set; }
        public Nullable<System.DateTime> date_registered { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string lastname { get; set; }
        public string civil_status { get; set; }
        public string address { get; set; }
        public string contact_no { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public string birth_place { get; set; }
        public string occupation { get; set; }
        public Nullable<decimal> credit_limit { get; set; }
        public Nullable<decimal> annual_income { get; set; }
    }
}
