//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lending_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_loan_type_charges
    {
        public int autonum { get; set; }
        public string description { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string charge_type { get; set; }
        public Nullable<int> loan_type_id { get; set; }
    }
}
